Repository codinasion/codinasion-programme, pull requests merged in 2022-02, with the labels that each got.

#32 add: content
  c/programmes/10 - factorial/README.md
  c/programmes/README.md
Labels: 📝 content

#35 update: .github
  .github/ISSUE_TEMPLATE/add-content.yml
  .github/ISSUE_TEMPLATE/improve-existing-content.yml
  .github/config.yml
  .github/workflows/60-days-stale-check.yml
  c/programmes/10 - factorial/README.md
Labels: documentation, 📝 content

#36 update: documentation
  CONTRIBUTING.md
  contributing/readme-template.md
  contributing/types-of-contributions.md
Labels: documentation

#48 swap two numbers without using third variable in c is crated
  c/programmes/11 - swap two numbers without using third varible/swapNumbers.c
Labels: good first issue, 📝 content, C

#49 add: /c/programmes/11
  c/programmes/11 - swap two numbers without using third varible/README.md
  c/programmes/11 - swap two numbers without using third varible/swapNumbers.c
  c/programmes/README.md
Labels: 📝 content

#50 update programmes folder
  .gitignore
  c/programmes/1 - display the equation/1.c
  c/programmes/11 - swap two numbers without using third varible/swapNumbers.c
  c/programmes/2 - print mailing address/2.c
  c/programmes/3 - multiplication table/3.c
  c/programmes/4 - display the value/4.c
  c/programmes/5 - convert celsius to fahrenheit/5.c
  github/awesome-readme-components/README.md
  github/how-to-setup-github-contribution-grid-snake/README.md
  python/programmes/1 - store the details of persons/1.py
Labels: 📝 content

#69 add: c/programme/7-number-to-string
  .gitignore
  c/programme/7-number-to-string/README.md
  c/programme/7-number-to-string/index.md
  c/programme/7-number-to-string/ntos.c
  c/programme/README.md
Labels: 📝 content, C

#71 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, ⭐ goal: addition

#94 fix: typo
  .github/ISSUE_TEMPLATE/add-content.yml
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/improve-existing-content.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation

#104 added swap two numbers program
  python/programme/README.md
  python/programme/swap-two-numbers/README.md
  python/programme/swap-two-numbers/index.md
  python/programme/swap-two-numbers/swap.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#152 Factorial of a number
  python/programme/4-factorial/README.md
  python/programme/4-factorial/factorial.py
  python/programme/4-factorial/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#157 Average
  python/programme/5-average-of-numbers/README.md
  python/programme/5-average-of-numbers/average.py
  python/programme/5-average-of-numbers/index.md
  python/programme/README.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#203 update #200
  python/programme/8-print-even-numbers/README.md
  python/programme/8-print-even-numbers/evennumbers.py
  python/programme/8-print-even-numbers/index.md
  python/programme/README.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#207 Fibonacci Series Python
  python/programme/10-fibonnaci/README.md
  python/programme/10-fibonnaci/fibonacci.py
  python/programme/10-fibonnaci/index.md
  python/programme/9-rupee-to-paise/README.md
  python/programme/9-rupee-to-paise/index.md
  python/programme/9-rupee-to-paise/rupeetopaise.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#213 Sum-of-digits(C++)
  c++/programme/README.md
  c++/programme/index.md
  c++/programme/sum-of-digits.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#215 Maximum of Numbers Python
  python/programme/12-maximum-of-numbers/README.md
  python/programme/12-maximum-of-numbers/index.md
  python/programme/12-maximum-of-numbers/max.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#216 Minimum of Numbers Python
  python/programme/13-minimum-of-numbers/README.md
  python/programme/13-minimum-of-numbers/index.md
  python/programme/13-minimum-of-numbers/min.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#218 Check Prime Number Python
  python/programme/check-prime-number/solution.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#256 Add sum of cubes python function
  python/programme/12-sum-of-cubes/README.md
  python/programme/12-sum-of-cubes/index.md
  python/programme/12-sum-of-cubes/sumcubes.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#259 Add Area of Circle Python Function
  programme/area-of-circle/README.md
  programme/area-of-circle/index.md
  programme/area-of-circle/solution.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#254 Solves issue #149 and #238
  c#/index.md
  c#/programme/1-minimum-of-numbers/1.cs
  c#/programme/1-minimum-of-numbers/README.md
  c#/programme/1-minimum-of-numbers/index.md
  c#/programme/2-ascii-value/2.cs
  c#/programme/2-ascii-value/README.md
  c#/programme/2-ascii-value/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C#

#260 ASCII Value
  programme/print-ASCII-value/ascii_value.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#255 sum-of-digits(c and java)
  programme/sum-of-digits/README.md
  programme/sum-of-digits/solution.c
  programme/sum-of-digits/solution.java
Labels: good first issue, 📝 content, C, ready-to-deploy, Java

#261 Add Compound Interest Calculator Python Function
  programme/compound-interest-calculator/README.md
  programme/compound-interest-calculator/index.md
  programme/compound-interest-calculator/solution.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#263 Added Sum of cube of first n number
  programme/README.md
  programme/Sum-of-cube/Readme.md
  programme/Sum-of-cube/SumOfCube.class
  programme/Sum-of-cube/SumOfCube.java
  programme/Sum-of-cube/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#264 ASCII Value #240
  programme/ascii-value/README.md
  programme/ascii-value/solution.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#270 Add swap two numbers python
  programme/README.md
  programme/swap-two-numbers/README.md
  programme/swap-two-numbers/index.md
  programme/swap-two-numbers/solution.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#268 fix #234: Added Area of Circle Java program to README.md
  programme/area-of-circle/README.md
  programme/area-of-circle/solution.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#273 Maximum of Numbers
  programme/maximum-of-numbers/solution.cs
Labels: good first issue, 📝 content, ready-to-deploy, C#
