Repository codinasion/codinasion-programme, pull requests merged in 2022-05, with the labels that each got.

#518 Added python file for checking armstrong number and updated readme fo…
  programme/armstrong-number/README.md
  programme/armstrong-number/armstrong-number.py
  programme/armstrong-number/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#519 Java area of trapezoid
  programme/area-of-trapezoid/AreaOfTrapezoid.java
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/index.md
  programme/fibonacci-pattern/FibonacciPattern.java
  programme/fibonacci-pattern/README.md
  programme/fibonacci-pattern/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#520 Added area of rhombus in c#
  programme/area-of-rhombus/README.md
  programme/area-of-rhombus/area-of-rhombus.cs
  programme/area-of-rhombus/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C#

#524 years-to-days
  programme/years-to-days/README.md
  programme/years-to-days/index.md
  programme/years-to-days/years-to-days.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#521 Created a C program for area of trapezoid
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/area-of-trapezoid.c
  programme/area-of-trapezoid/area-of-trapezoid.java
  programme/area-of-trapezoid/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#534 C program for volume of cylinder
  programme/volume-of-cylinder/README.md
  programme/volume-of-cylinder/index.md
  programme/volume-of-cylinder/volume-of-cylinder.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#535 Python solution to calculate volume of cylinder
  programme/volume-of-cylinder/README.md
  programme/volume-of-cylinder/index.md
  programme/volume-of-cylinder/volume-of-cylinder.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#538 HoursToSeconds
  programme/hours-to-seconds/README.md
  programme/hours-to-seconds/hourstoseconds.java
  programme/hours-to-seconds/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#536 adding volume-of-cylinder (java)
  programme/area-of-rectangle/README.md
  programme/area-of-rectangle/areaOfRectangle.java
  programme/area-of-rectangle/index.md
  programme/volume-of-cylinder/README.md
  programme/volume-of-cylinder/index.md
  programme/volume-of-cylinder/volumeOfCylinder.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#532 Java average
  programme/alphabet-triangle-pattern/AlphaTrianglePattern.java
  programme/area-of-circle/AreaOfCircle.java
  programme/area-of-right-angle-triangle/RightTriangleArea.java
  programme/area-of-square/AreaOfSquare.java
  programme/area-of-trapezoid/AreaOfTrapezoid.java
  programme/area-of-triangle/AreaOfTriangle.java
  programme/armstrong-number/ArmstrongNumber.java
  programme/ascii-value/ASCIIValue.java
  programme/average-of-numbers/AverageOfNumbers.java
  programme/average-of-numbers/README.md
  programme/average-of-numbers/index.md
  programme/celsius-to-fahrenheit/CelsiusToFahrenheit.java
  programme/check-prime-number/CheckPrime.java
  programme/compound-interest-calculator/CompoundInterest.java
  programme/decimal-to-binary/DecimalToBinary.java
  programme/divide-two-numbers/DivideTwoNums.java
  programme/factorial/Factorial.java
  programme/fibonaci-series-without-using-recursion/Fibonacci.java
  programme/fibonnaci-series-using-recursion/FibonacciRecursion.java
  programme/length-of-string/StringLength.java
  programme/minimum-of-numbers/MinOfNumbers.java
  programme/number-to-string/NumberToString.java
  programme/number-triangle-pattern/NumTrianglePattern.java
  programme/palindrome-number/Palindrome.java
  programme/pattern-2/Pattern2.java
  programme/perimeter-of-rectangle/PerimeterOfRectangle.java
  programme/perimeter-of-square/PerimeterOfSquare.java
  programme/reverse-of-a-number/ReverseOfNumber.java
  programme/rupee-to-paise/RupeeToPaise.java
  programme/square-of-number/SquareOfNum.java
  programme/subtract-two-numbers/SubtractTwoNums.java
  programme/sum-of-cubes/SumOfCube.java
  programme/sum-of-digits/SumOfDigits.java
  programme/sum-of-square/SumOfSquare.java
  programme/swap-two-numbers-without-using-third-variable/Swap.java
  programme/years-to-days/YearsToDays.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#537 Volume of a cylinder: C++ program
  programme/volume-of-cylinder/README.md
  programme/volume-of-cylinder/index.md
  programme/volume-of-cylinder/volume-of-cylinder.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#546 Sphere Volume: compute with Python
  .gitignore
  programme/volume-of-sphere/README.md
  programme/volume-of-sphere/volume-of-sphere.py
Labels: good first issue, 📝 content, Python

#545 Solution to maxnumbers
  programme/maximum-of-numbers/MaximumOfNumbers.java
  programme/maximum-of-numbers/README.md
Labels: good first issue, 📝 content, Java

#552 Added perimeter-of-rectangle.cpp
  programme/area-of-rhombus/README.md
  programme/area-of-rhombus/area-of-rhombus.cpp
  programme/perimeter-of-rectangle/README.md
  programme/perimeter-of-rectangle/perimeter-of-rectangle.cpp
Labels: good first issue, 📝 content, C++

#557 changed title to Alphabet triangle pattern
  programme/alphabet-triangle-pattern/README.md
Labels: good first issue, 📝 content, 🛠 goal: fix

#554 Added a Java file for add two numbers
  programme/add-two-numbers/AddTwoNumbers.java
  programme/add-two-numbers/README.md
  programme/volume-of-sphere/README.md
  programme/volume-of-sphere/volume-of-sphere.c
  programme/volume-of-sphere/volume-of-sphere.cpp
Labels: good first issue, 📝 content, Java

#561 Hello-World Java Issue
  programme/hello-world/README.md
  programme/hello-world/hello_world.java
Labels: good first issue, 📝 content, Java

#560 Golang two numbers
  programme/add-two-numbers/README.md
  programme/add-two-numbers/add-two-numbers.go
Labels: good first issue, 📝 content, GO

#563 Cpp area of trapezoid
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/area-of-trapezoid.cpp
Labels: good first issue, 📝 content, C++

#614 added number to string javascript file
  programme/number-to-string/README.md
  programme/number-to-string/number-to-string.js
Labels: 📝 content, JavaScript

#616 Added helloworld.go
  programme/hello-world/README.md
  programme/hello-world/helloworld.go
Labels: 📝 content, GO

#617 Go - Hours to seconds
  programme/hours-to-seconds/README.md
  programme/hours-to-seconds/hourstoseconds.go
Labels: 📝 content, GO

#618 complete hours to seconds solution in JavaScript
  programme/hours-to-seconds/README.md
  programme/hours-to-seconds/hours-to-seconds.js
Labels: 📝 content, JavaScript

#619 Adds area of triangle in JavaScript file.
  programme/area-of-triangle/README.md
  programme/area-of-triangle/area-of-triangle.js
Labels: 📝 content, JavaScript

#620 Added factorial.js
  programme/factorial/README.md
  programme/factorial/factorial.js
Labels: 📝 content, JavaScript

#621 added divide-two-numbers.js
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide-two-numbers.js
Labels: 📝 content, JavaScript

#622 fibonacci pattern in go
  programme/fibonacci-pattern/README.md
  programme/fibonacci-pattern/fibonacci_pattern.go
Labels: 📝 content, GO

#623 Added compound-interest.js
  programme/compound-interest-calculator/README.md
  programme/compound-interest-calculator/compound-interest.js
Labels: 📝 content, JavaScript

#624 Cpp divide two numbers
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide-two-numbers.cpp
Labels: 📝 content, C++

#625 Tosin
  programme/multiplication-table/README.md
  programme/multiplication-table/table.py
Labels: 📝 content, Python

#633 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#634 Added C Program for 'Add two numbers'
  programme/add-two-numbers/README.md
  programme/add-two-numbers/add-two-numbers.c
Labels: 📝 content, C

#635 added factorial of a number using C++
  programme/factorial/README.md
  programme/factorial/factorial.cpp
Labels: 📝 content, C++

#637 Added C Program for 'Area of circle'
  programme/area-of-circle/README.md
  programme/area-of-circle/area-of-circle.c
Labels: 📝 content, C

#638 Added C Program for 'Mulitply two numbers'
  programme/multiply-two-numbers/README.md
  programme/multiply-two-numbers/multiply.c
Labels: 📝 content, C

#636 Added Java Program
  programme/multiplication-table/MultiplicationTable.java
  programme/multiplication-table/README.md
  programme/multiplication-table/table.cpp
Labels: 📝 content, C++, Java

#639 program to find multiplicatiom table
  programme/multiplication-table/README.md
  programme/multiplication-table/table1.cpp
Labels: 📝 content, C++

#641 Added C# Multiplication Table
  programme/multiplication-table/MultiplicationTable.cs
  programme/multiplication-table/README.md
Labels: 📝 content, C#

#648 Create AlphabetTrianglePattern.cs
  programme/alphabet-triangle-pattern/AlphabetTrianglePattern.cs
  programme/alphabet-triangle-pattern/README.md
Labels: 📝 content, C#

#649 Add: C code for swap 2 numbers
  programme/swap-two-numbers/README.md
  programme/swap-two-numbers/solution.c
Labels: 📝 content, C

#650 JS solution to Issue #600
  programme/harmonic-series/README.md
  programme/harmonic-series/harmonic-series.js
Labels: 📝 content, JavaScript

#652 Added HelloWorld.cs
  programme/hello-world/HelloWorld.cs
  programme/hello-world/README.md
Labels: 📝 content, C#

#651 eulers-number.js #598
  programme/area-of-rectangle/README.md
  programme/area-of-rectangle/area-of-rectangle.js
  programme/euler-number/README.md
  programme/euler-number/euler-number.js
Labels: 📝 content, JavaScript

#653 Added sum-of-digits.cs
  programme/sum-of-digits/README.md
  programme/sum-of-digits/sum-of-digits.cs
Labels: 📝 content, C#

#660 Some c++ issues fixed
  programme/fibonacci-pattern/README.md
  programme/fibonacci-pattern/fibonacci_pattern.cpp
  programme/minutes-to-seconds/README.md
  programme/minutes-to-seconds/minutes-to-seconds.cpp
Labels: 📝 content, C++

#663 Added simple_interest_calculator.py
  programme/simple-interest-calculator/README.md
  programme/simple-interest-calculator/simple_interest_calculator.py
Labels: 📝 content, Python

#654 Digital Root Added
  programme/digital-root/README.md
  programme/digital-root/digital_root.c
  programme/digital-root/digital_root.cpp
  programme/digital-root/digital_root.py
Labels: 📝 content, C, Python, C++

#656 Added ArmstrongNumber for C#
  programme/armstrong-number/ArmstrongNumber.cs
  programme/armstrong-number/README.md
Labels: 📝 content, C#

#675 Solve recursive fibonacci problem in JavaScript
  programme/fibonnaci-series-using-recursion/README.md
  programme/fibonnaci-series-using-recursion/fibonacci_recursion.js
Labels: 📝 content, JavaScript

#674 Solve Fibonacci Pattern Problem in JavaScript
  programme/fibonacci-pattern/README.md
  programme/fibonacci-pattern/fibonacci_pattern.js
Labels: 📝 content, JavaScript

#673 Implement the digital root using Ramans formula in Java. Resolves iss…
  programme/digital-root/README.md
  programme/digital-root/digital_root.java
Labels: 📝 content, Java

#678 Add digital_root.js
  programme/digital-root/README.md
  programme/digital-root/digital_root.js
Labels: 📝 content, JavaScript

#676 JavaScript - added hello-world and fibonacci-pattern
  programme/fibonacci-pattern/fibonacci-pattern.js
  programme/hello-world/README.md
  programme/hello-world/hello-world.js
Labels: 📝 content, JavaScript

#679 Implement check-prime in JavaScript
  programme/check-prime-number/README.md
  programme/check-prime-number/check-prime.js
Labels: 📝 content, JavaScript

#680 programme for adding 2 numbes in javascript
  programme/add-two-numbers/README.md
  programme/add-two-numbers/add-two-numbers.js
Labels: 📝 content, JavaScript

#681 Added Area of circle, rectangle, and rhombus in C#
  programme/area-of-circle/AreaOfCircle.cs
  programme/area-of-circle/README.md
  programme/area-of-rectangle/AreaOfRectangle.cs
  programme/area-of-rectangle/README.md
  programme/area-of-rhombus/AreaOfRhombus.cs
  programme/area-of-rhombus/README.md
Labels: 📝 content, C#

#682 Added armstrong-number.js
  programme/armstrong-number/README.md
  programme/armstrong-number/armstrong-number.js
  programme/armstrong-number/armstrongnumber.go
Labels: 📝 content, GO, JavaScript

#684 Added C and CPP program of Square of a Number
  programme/square-of-number/README.md
  programme/square-of-number/square_of_a_number.c
  programme/square-of-number/square_of_a_number.cpp
Labels: 📝 content, C, C++

#683 Added sum of square in JS
  programme/sum-of-square/README.md
  programme/sum-of-square/SumOfSquare .js
Labels: 📝 content, JavaScript

#677 Create matrix_multiplication.py
  programme/matrix-multiplication/README.md
  programme/matrix-multiplication/matrix_multiplication.py
Labels: 📝 content, Python

#694 update docs
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/60-days-stale-check.yml
  .github/workflows/pr-merge-comment.yml
  CONTRIBUTING.md
Labels: documentation

#695 Implement Alphabet Triangle Pattern in JavaScript
  programme/alphabet-triangle-pattern/README.md
  programme/alphabet-triangle-pattern/alphabet-triangle-pattern.js
Labels: 📝 content, JavaScript

#696 Pangram Checker Program added
  programme/pangram-checker/README.md
  programme/pangram-checker/pangram-checker.c
  programme/pangram-checker/pangram-checker.cpp
Labels: 📝 content, C, C++

#697 Docs update
  CONTRIBUTING.md
  contributing/types-of-contributions.md
Labels: documentation

#698 Go - Added area of circle, rectangle, triangle and right triangle
  programme/area-of-circle/README.md
  programme/area-of-circle/areaofcircle.go
  programme/area-of-rectangle/README.md
  programme/area-of-rectangle/areaofrectangle.go
  programme/area-of-right-angle-triangle/README.md
  programme/area-of-right-angle-triangle/areaofrightangletriangle.go
  programme/area-of-triangle/README.md
  programme/area-of-triangle/areaoftriangle.go
Labels: 📝 content, GO

#699 Added Multiplication of Two Matrix
  programme/matrix-multiplication/README.md
  programme/matrix-multiplication/matrix_multiplication.c
  programme/matrix-multiplication/matrix_multiplication.cpp
Labels: 📝 content, C, C++

#702 Add pangram-checker.py
  programme/pangram-checker/README.md
  programme/pangram-checker/pangram-checker.py
Labels: 📝 content, Python

#700 Matrix Multiplication - Java
  programme/area-of-rectangle/AreaOfRectangle.java
  programme/area-of-rectangle/README.md
  programme/digital-root/DigitalRoot.java
  programme/digital-root/README.md
  programme/hello-world/HelloWorld.java
  programme/hello-world/README.md
  programme/matrix-multiplication/MatrixMultiplication.java
  programme/matrix-multiplication/README.md
Labels: 📝 content, Java
