Repository codinasion/codinasion-programme, pull requests merged in 2022-06, with the labels that each got.

#705 Added swap_without_temp.go
  programme/swap-two-numbers-without-using-third-variable/README.md
  programme/swap-two-numbers-without-using-third-variable/swap_without_temp.go
Labels: 📝 content, GO

#706 added the divide-two-numbers in golang
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide-two-numbers.go
Labels: 📝 content, GO

#707 Added area-of-circle.js
  programme/area-of-circle/README.md
  programme/area-of-circle/area-of-circle.js
Labels: 📝 content, JavaScript

#708 Added palindrome.go
  programme/palindrome-number/README.md
  programme/palindrome-number/palindrome.go
Labels: 📝 content, GO

#709 Added palindrome.js
  programme/palindrome-number/README.md
  programme/palindrome-number/palindrome.js
Labels: 📝 content, JavaScript

#711 Harmonic series
  programme/harmonic-series/HarmonicSeries.java
  programme/harmonic-series/README.md
  programme/harmonic-series/harmonic-series.cpp
  programme/harmonic-series/harmonic-series.py
Labels: 📝 content, Python, C++, Java

#712 Cpp programs
  programme/armstrong-number/README.md
  programme/armstrong-number/armstrong-number.cpp
  programme/print-even-numbers/README.md
  programme/print-even-numbers/print-even.cpp
  programme/simple-interest-calculator/README.md
  programme/simple-interest-calculator/simple-interest-calculator.cpp
  programme/years-to-days/README.md
  programme/years-to-days/years-to-days.cpp
Labels: 📝 content, C++

#713 Implement pattern-2 in JavaScript
  programme/pattern-2/README.md
  programme/pattern-2/pattern-2.js
Labels: 📝 content, JavaScript

#714 created the sum-of-squares program in golang
  programme/sum-of-square/README.md
  programme/sum-of-square/sum-of-squares.go
Labels: 📝 content, GO

#715 Added FibonacciPattern.cs
  programme/fibonacci-pattern/FibonacciPattern.cs
  programme/fibonacci-pattern/README.md
Labels: 📝 content, C#

#716 Added CompoundInterest.cs
  programme/compound-interest-calculator/CompoundInterest.cs
  programme/compound-interest-calculator/README.md
Labels: 📝 content, C#

#717 add js function for square of a num
  programme/square-of-number/README.md
  programme/square-of-number/square-of-a-num.js
Labels: 📝 content, JavaScript

#723 Created area of Square.go file
  programme/area-of-square/README.md
  programme/area-of-square/area-of-square.go
Labels: 📝 content, GO

#735 add og image for pangram-checker
  programme/pangram-checker/hero.png
Labels: enhancement

#725 Created area-of-trapezoid.go file
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/area-of-trapezoid.go
Labels: 📝 content, GO

#726 Created area-of-rhombus.go file
  programme/area-of-rhombus/README.md
  programme/area-of-rhombus/area-of-rhombus.go
Labels: 📝 content, GO

#737 Create area-of-rhombus.js
  programme/area-of-rhombus/README.md
  programme/area-of-rhombus/area-of-rhombus.js
Labels: 📝 content, JavaScript

#736 add sum of cube function for JS
  programme/sum-of-cubes/README.md
  programme/sum-of-cubes/sum-of-cube.js
Labels: 📝 content, JavaScript

#738 Find any ASCII value of any character
  programme/ascii-value/README.md
  programme/ascii-value/ascii-value.go
Labels: 📝 content, GO

#784 Added java program for even or odd number
  programme/even-or-odd-number/EvenOrOdd.java
  programme/even-or-odd-number/README.md
Labels: 📝 content, Java

#786 Added merge-strings
  programme/merge-strings/README.md
  programme/merge-strings/mergeStrings.c
  programme/merge-strings/mergeStrings.cpp
  programme/merge-strings/mergeStrings.java
  programme/merge-strings/mergeStrings.js
  programme/merge-strings/mergeStrings.py
Labels: 📝 content, C, Python, C++, Java, JavaScript

#787 Celsius to Fahrenheit conversion
  programme/celsius-to-fahrenheit/README.md
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.go
Labels: 📝 content, GO

#788 Check input is leap year or not
  programme/check-leap-year/README.md
  programme/check-leap-year/check-leap-year.go
Labels: 📝 content, GO

#789 Added VolumeOfSphere.cs
  programme/volume-of-sphere/README.md
  programme/volume-of-sphere/VolumeOfSphere.cs
Labels: 📝 content, C#

#790 Added merge-two-strings for C#
  programme/merge-two-strings/MergeTwoStrings.cs
  programme/merge-two-strings/README.md
Labels: 📝 content, C#

#796 Added swap-wtihout-temp.cs
  programme/swap-two-numbers-without-using-third-variable/README.md
  programme/swap-two-numbers-without-using-third-variable/swap-without-temp.cs
Labels: 📝 content, C#

#798 Added SimpleInterestCalculator.cs
  programme/simple-interest-calculator/README.md
  programme/simple-interest-calculator/SimpleInterestCalculator.cs
Labels: 📝 content, C#

#799 Added number-to-string.cs
  programme/number-to-string/README.md
  programme/number-to-string/number-to-string.cs
Labels: 📝 content, C#

#802 Leap year js
  programme/check-leap-year/README.md
  programme/check-leap-year/check-leap-year.js
Labels: 📝 content, JavaScript

#805 Merge two string go
  programme/merge-two-strings/README.md
  programme/merge-two-strings/mergeStrings.go
Labels: 📝 content, GO

#806 JavaScript even-or-odd solution
  programme/even-or-odd-number/README.md
  programme/even-or-odd-number/even-or-odd.js
Labels: 📝 content, JavaScript

#817 Added average-of-numbers.cs
  programme/average-of-numbers/README.md
  programme/average-of-numbers/average-of-numbers.cs
Labels: 📝 content, C#

#818 Added print-even.cs
  programme/print-even-numbers/README.md
  programme/print-even-numbers/print-even.cs
Labels: 📝 content, C#

#819 CelcToFahr
  programme/celsius-to-fahrenheit/README.md
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.js
Labels: 📝 content, JavaScript

#821 add area of square function for JS
  programme/area-of-square/README.md
  programme/area-of-square/area-of-square.js
Labels: 📝 content, JavaScript

#822 Added number-to-string.go
  programme/number-to-string/README.md
  programme/number-to-string/number-to-string.go
Labels: 📝 content, GO

#804 Added negative-of-number.py and negative-of-number.cpp
  programme/negative-of-a-number/README.md
  programme/negative-of-a-number/negative-of-a-number.cpp
  programme/negative-of-a-number/negative-of-a-number.py
Labels: 📝 content, Python, C++, og required

#807 count size of array
  programme/array-size/README.md
  programme/array-size/array-size.js
  programme/array-size/array-size.php
  programme/array-size/array-size.py
Labels: 📝 content, Python, JavaScript, PHP, og required

#820 C programs
  programme/even-or-odd-number/README.md
  programme/even-or-odd-number/even-or-odd.c
  programme/feet-to-inches/README.md
  programme/feet-to-inches/feet-to-inches.c
  programme/inches-to-feet/README.md
  programme/inches-to-feet/inches-to-feet.c
Labels: 📝 content, C, og required

#829 Count size of array
  programme/array-size/README.md
  programme/array-size/array-size.java
Labels: 📝 content, Java

#830 Feet to inches
  programme/feet-to-inches/FeetToInches.java
  programme/feet-to-inches/README.md
  programme/feet-to-inches/feet-to-inches.cpp
  programme/feet-to-inches/feet-to-inches.js
  programme/feet-to-inches/feet-to-inches.py
Labels: 📝 content, Python, C++, Java, JavaScript

#831 A program that converts decimal to binary
  programme/decimal-to-binary/README.md
  programme/decimal-to-binary/decimal-to-binary.go
Labels: 📝 content, GO

#832 a program that returns digital root of a number
  programme/digital-root/README.md
  programme/digital-root/digital_root.go
Labels: 📝 content, GO

#833 Added a C# program to return the size of an array
  programme/array-size/README.md
  programme/array-size/array-size.cs
Labels: 📝 content, C#

#834 Added print-even.js
  programme/print-even-numbers/README.md
  programme/print-even-numbers/print-even.js
Labels: 📝 content, JavaScript

#836 Added fibonaci-recursion.go
  programme/fibonnaci-series-using-recursion/README.md
  programme/fibonnaci-series-using-recursion/fibonaci-recursion.go
Labels: 📝 content, GO

#837 Factorial of a number
  programme/factorial/README.md
  programme/factorial/factorial.go
Labels: 📝 content, GO

#838 Added minutes-to-seconds.go
  programme/minutes-to-seconds/README.md
  programme/minutes-to-seconds/minutes-to-seconds.go
Labels: 📝 content, GO

#840 Added negative-of-a-number.go
  programme/negative-of-a-number/README.md
  programme/negative-of-a-number/negative-of-a-number.go
Labels: 📝 content, GO

#844 Added NegativeOfANumber.java
  programme/negative-of-a-number/NegativeOfANumber.java
  programme/negative-of-a-number/README.md
Labels: 📝 content, Java

#843 Finished the print-even golang program
  programme/print-even-numbers/README.md
  programme/print-even-numbers/print-even.go
Labels: 📝 content, GO

#842 Added even-or-odd.go
  programme/even-or-odd-number/README.md
  programme/even-or-odd-number/even-or-odd.go
Labels: 📝 content, GO

#851 Added rs-to-p.cs
  programme/rupee-to-paise/README.md
  programme/rupee-to-paise/rs-to-p.cs
Labels: 📝 content, C#

#854 Closes #809
  programme/array-size/README.md
  programme/array-size/array-size.cpp
Labels: 📝 content, C++

#853 Added sum-of-square.cs
  programme/sum-of-square/README.md
  programme/sum-of-square/sum-of-square.cs
Labels: 📝 content, C#

#855 Find the length of the string
  programme/length-of-string/README.md
  programme/length-of-string/length-of-string-with-built-in-func.go
Labels: 📝 content, GO

#839 Created harmonic-series.go
  programme/harmonic-series/README.md
  programme/harmonic-series/harmonic-series.go
Labels: 📝 content, GO

#857 Add go code for fetching the length of an array
  programme/array-size/README.md
  programme/array-size/array-size.go
  programme/even-or-odd-number/README.md
  programme/even-or-odd-number/even-or-odd.py
Labels: 📝 content, Python, GO

#858 Length of an array
  programme/array-size/README.md
  programme/array-size/array-size.c
  programme/array-size/array-size1.cpp
Labels: 📝 content, C, C++

#863 Add length-of-string.js
  programme/length-of-string/README.md
  programme/length-of-string/length-of-string.js
Labels: 📝 content, JavaScript

#864 Added rs-to-p.go
  programme/rupee-to-paise/README.md
  programme/rupee-to-paise/rs-to-p.go
Labels: 📝 content, GO

#865 Added square-of-a-number.go
  programme/square-of-number/README.md
  programme/square-of-number/square-of-a-number.go
Labels: 📝 content, GO

#866 Issue197/fibonaci recursion
  programme/fibonnaci-series-using-recursion/README.md
  programme/fibonnaci-series-using-recursion/fibonaci-recursion.cs
Labels: 📝 content, C#

#867 Added digital_root.cs
  programme/digital-root/README.md
  programme/digital-root/digital_root.cs
Labels: 📝 content, C#

#868 Added hours-to-seconds.cs
  programme/hours-to-seconds/README.md
  programme/hours-to-seconds/hours-to-seconds.cs
Labels: 📝 content, C#

#870 Added sum-of-cube.cs
  programme/sum-of-cubes/README.md
  programme/sum-of-cubes/sum-of-cube.cs
Labels: 📝 content, C#

#871 Add inches-to-feet.go
  programme/inches-to-feet/README.md
  programme/inches-to-feet/inches-to-feet.go
Labels: 📝 content, GO

#872 Add feet-to-inches.go
  programme/feet-to-inches/README.md
  programme/feet-to-inches/feet-to-inches.go
Labels: 📝 content, GO

#873 add JS function to calculate area of trapezoid
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/area-of-trapezoid.js
Labels: 📝 content, JavaScript

#869 Added minutes-to-seconds.cs
  programme/minutes-to-seconds/README.md
  programme/minutes-to-seconds/minutes-to-seconds.cs
Labels: 📝 content, C#

#875 Add InchesToFeet.cs
  programme/inches-to-feet/InchesToFeet.cs
  programme/inches-to-feet/README.md
Labels: 📝 content, C#

#876 Add FeetToInches.cs
  programme/feet-to-inches/FeetToInches.cs
  programme/feet-to-inches/README.md
Labels: 📝 content, C#

#877 Add Palindrome.cs
  programme/palindrome-number/Palindrome.cs
  programme/palindrome-number/README.md
Labels: 📝 content, C#

#878 Added check-leap-year.cs
  programme/check-leap-year/README.md
  programme/check-leap-year/check-leap-year.cs
Labels: 📝 content, C#

#879 Added check-prime.cs
  programme/check-prime-number/README.md
  programme/check-prime-number/check-prime.cs
Labels: 📝 content, C#

#881 Added ascii-value.js which returns the value of a character in ASCII value
  programme/ascii-value/README.md
  programme/ascii-value/ascii-value.js
Labels: 📝 content, JavaScript

#882 Added pangram-checker.go
  programme/pangram-checker/README.md
  programme/pangram-checker/pangram-checker.go
Labels: 📝 content, GO

#886 Minutes to Seconds JS implementation
  programme/minutes-to-seconds/README.md
  programme/minutes-to-seconds/minutes-to-seconds.js
Labels: 📝 content, JavaScript

#887 Added a C# program to calculate the volume of cylinder
  programme/volume-of-cylinder/README.md
  programme/volume-of-cylinder/volume-of-cylinder.cs
Labels: 📝 content, C#

#892 Added sum-of-cubes.go
  programme/sum-of-cubes/README.md
  programme/sum-of-cubes/sum-of-cubes.go
Labels: 📝 content, GO

#893 Added sum-of-digits.go
  programme/sum-of-digits/README.md
  programme/sum-of-digits/sum-of-digits.go
Labels: 📝 content, GO

#894 Added pangram-checker.cs
  programme/pangram-checker/README.md
  programme/pangram-checker/pangram-checker.cs
Labels: 📝 content, C#

#895 Added pattern-2.cs
  programme/pattern-2/README.md
  programme/pattern-2/pattern-2.cs
Labels: 📝 content, C#

#861 find negative number
  programme/array-elements-slice/README.md
  programme/array-elements-slice/array-elements-slice.js
  programme/array-elements-slice/array-elements-slice.php
  programme/array-elements-slice/array-elements-slice.py
  programme/negative-of-a-number/README.md
  programme/negative-of-a-number/find-negative-number.js
  programme/negative-of-a-number/find-negative-number.php
  programme/negative-of-a-number/find-negative-number.py
Labels: 📝 content, Python, JavaScript, PHP

#835 A function to print array in slice mode
  programme/array-elements-slice/array-elements-slice.js
  programme/array-elements-slice/array-elements-slice.php
  programme/array-elements-slice/array-elements-slice.py
Labels: 🚦 status: awaiting triage

#911 added even-or-odd for c++
  programme/even-or-odd-number/README.md
  programme/even-or-odd-number/even-or-odd.cpp
Labels: 📝 content, C++

#912 Slice array element in go #903
  programme/array-elements-slice/README.md
  programme/array-elements-slice/array-elements-slice.go
Labels: 📝 content, GO
