Repository codinasion/codinasion-programme, pull requests merged in 2022-04, with the labels that each got.

#411 Add : alphabet triangle programme
  programme/README.md
  programme/alphabet-triangle-pattern/README.md
  programme/alphabet-triangle-pattern/alphabet-triangle-pattern.c
  programme/alphabet-triangle-pattern/alphabet-triangle-pattern.cpp
  programme/alphabet-triangle-pattern/alphabet-triangle-pattern.py
  programme/alphabet-triangle-pattern/alphabet_triangle_pattern.java
  programme/alphabet-triangle-pattern/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy, Python, C++, Java

#414 Seraph branch
  programme/README.md
  programme/minutes-to-seconds/README.md
  programme/minutes-to-seconds/index.md
  programme/minutes-to-seconds/minutes-to-seconds.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#416 Added check-leap-year.cpp
  programme/check-leap-year/README.md
  programme/check-leap-year/check-leap-year.cpp
  programme/check-leap-year/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#415 created the hello-world in python and added to the hello-world folder
  programme/hello-world/README.md
  programme/hello-world/hello-world.py
  programme/hello-world/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#413 :sparkles::racehorse: Created Fibonacci sequence with Recursive for C++ #196
  programme/fibonnaci-series-using-recursion/README.md
  programme/fibonnaci-series-using-recursion/fibonacci.cpp
  programme/fibonnaci-series-using-recursion/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#431 Seraph branch
  programme/pattern-3/README.md
  programme/pattern-3/index.md
  programme/pattern-3/pattern-3.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#439 added perimeter-of-rectangle
  programme/perimeter-of-rectangle/README.md
  programme/perimeter-of-rectangle/index.md
  programme/perimeter-of-rectangle/perimeter-of-rectangle.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#447 Added C# Years to Days (Issue #426)
  programme/README.md
  programme/years-to-days/README.md
  programme/years-to-days/index.md
  programme/years-to-days/years-to-days.cs
Labels: good first issue, 📝 content, ready-to-deploy, C#

#446 added hours-to-seconds.cpp and hours-to-seconds.c
  programme/hours-to-seconds/README.md
  programme/hours-to-seconds/hours-to-seconds.c
  programme/hours-to-seconds/hours-to-seconds.cpp
  programme/hours-to-seconds/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy, C++

#449 Create hello-world.cpp
  programme/hello-world/README.md
  programme/hello-world/hello-world.cpp
  programme/hello-world/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#448 440
  programme/perimeter-of-square/README.md
  programme/perimeter-of-square/index.md
  programme/perimeter-of-square/perimeter-of-square.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#450 added perimeter-of-square folder and python program for the same purpose
  programme/perimeter-of-square/README.md
  programme/perimeter-of-square/index.md
  programme/perimeter-of-square/perimeter-of-square.py
  programme/years-to-days/README.md
  programme/years-to-days/index.md
  programme/years-to-days/years-to-days.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#452 Seraph branch
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide_two_numbers.py
  programme/divide-two-numbers/index.md
  programme/palindrome-number/README.md
  programme/palindrome-number/check_palindrome.py
  programme/palindrome-number/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#459 Added C# version of fibonaci series without recursion
  programme/fibonaci-series-without-using-recursion/README.md
  programme/fibonaci-series-without-using-recursion/fibonaci.cs
  programme/fibonaci-series-without-using-recursion/index.md
Labels: help wanted, good first issue, 📝 content, ready-to-deploy, C#

#460 Add swap two numbers without using third variable C++
  programme/swap-two-numbers-without-using-third-varible/README.md
  programme/swap-two-numbers-without-using-third-varible/index.md
  programme/swap-two-numbers-without-using-third-varible/swap-without-temp.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#461 worked on issue: Length of string #457
  programme/length-of-a-string/README.md
  programme/length-of-a-string/index.md
  programme/length-of-a-string/length.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#462 34
  programme/factorial/README.md
  programme/factorial/factorial.c
  programme/factorial/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#463 37
  programme/armstrong-number/README.md
  programme/armstrong-number/armstrong-number.c
  programme/armstrong-number/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#464 Seraph branch
  programme/celsius-to-fahrenheit/README.md
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.c
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.py
  programme/celsius-to-fahrenheit/index.md
  programme/celsius-to-fahrenheit/temperature.c
  programme/number-to-string/README.md
  programme/number-to-string/index.md
  programme/number-to-string/numbers_to_string.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#465 Added C# version of Length of string (Issue #455)
  programme/length-of-string/README.md
  programme/length-of-string/index.md
  programme/length-of-string/length-of-string.cs
Labels: good first issue, 📝 content, ready-to-deploy, C#

#466 453
  programme/length-of-string/README.md
  programme/length-of-string/index.md
  programme/length-of-string/length-of-string.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#473 Add minimum of numbers C++
  programme/minimum-of-numbers/README.md
  programme/minimum-of-numbers/index.md
  programme/minimum-of-numbers/min.cpp
Labels: help wanted, good first issue, 📝 content, ready-to-deploy, C++

#474 Added C++ version of length of string
  programme/length-of-a-string/README.md
  programme/length-of-a-string/index.md
  programme/length-of-a-string/length.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#475 Celsius to Fahrenheit #468
  programme/celsius-to-fahrenheit/README.md
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.cpp
  programme/celsius-to-fahrenheit/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#477 moved files
  programme/celsius-to-fahrenheit/README.md
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.java
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit1.c
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit1.cpp
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit1.py
  programme/celsius-to-fahrenheit/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy, Python, C++, Java

#478 Completed issue #441
  programme/perimeter-of-square/README.md
  programme/perimeter-of-square/index.md
  programme/perimeter-of-square/perimeter-of-square.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#479 Resolves #95: Python program for calculating e
  programme/README.md
  programme/euler-number/README.md
  programme/euler-number/eulerNumber.py
  programme/euler-number/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#482 58
  programme/harmonic-series/README.md
  programme/harmonic-series/harmonic-series.c
  programme/harmonic-series/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#480 Resolves #469 Celsius to Fahrenheit C#
  programme/celsius-to-fahrenheit/README.md
  programme/celsius-to-fahrenheit/celsius-to-fahrenheit.cs
  programme/celsius-to-fahrenheit/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C#

#484 Added files for string length
  programme/length-of-string/README.md
  programme/length-of-string/index.md
  programme/length-of-string/length-of-string.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#488 Have a coookie perimeter
  programme/perimeter-of-square/README.md
  programme/perimeter-of-square/index.md
  programme/perimeter-of-square/perimiterofsquare.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#487 Swap without temp java
  programme/swap-two-numbers-without-using-third-variable/README.md
  programme/swap-two-numbers-without-using-third-variable/index.md
  programme/swap-two-numbers-without-using-third-variable/swap-without-temp.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#486 perimeter of rectangle java
  programme/perimeter-of-rectangle/README.md
  programme/perimeter-of-rectangle/index.md
  programme/perimeter-of-rectangle/perimeter-of-rectangle.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#490 424
  programme/years-to-days/README.md
  programme/years-to-days/index.md
  programme/years-to-days/years-to-days.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#491 368
  programme/area-of-triangle/README.md
  programme/area-of-triangle/area-of-triangle.c
  programme/area-of-triangle/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#492 242
  programme/sum-of-square/README.md
  programme/sum-of-square/index.md
  programme/sum-of-square/sum-of-square.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#493 Armstrong number java
  programme/armstrong-number/README.md
  programme/armstrong-number/armstrong-number.java
  programme/armstrong-number/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#494 C# Perimeter of Square
  programme/perimeter-of-square/README.md
  programme/perimeter-of-square/index.md
  programme/perimeter-of-square/perimeter-of-square.cs
Labels: good first issue, 📝 content, ready-to-deploy, C#

#495 added perimeter of rectangle code in c#
  programme/perimeter-of-rectangle/README.md
  programme/perimeter-of-rectangle/index.md
  programme/perimeter-of-rectangle/perimeter-of-rectangle.cs
Labels: good first issue, 📝 content, ready-to-deploy, C#

#507 Create area-of-trapezoid.cs
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/area-of-trapezoid.cs
  programme/area-of-trapezoid/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C#

#506 Create area-of-rhombus.py
  programme/area-of-rhombus/README.md
  programme/area-of-rhombus/area-of-rhombus.py
  programme/area-of-rhombus/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#504 Area-of-trapezoid for python
  programme/area-of-trapezoid/README.md
  programme/area-of-trapezoid/area-of-trapezoid.py
  programme/area-of-trapezoid/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#517 Update AreaOfRhombus.java
  programme/area-of-rhombus/AreaOfRhombus.java
  programme/area-of-rhombus/README.md
  programme/area-of-rhombus/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java
