Repository codinasion/codinasion-programme, pull requests merged in 2022-03, with the labels that each got.

#277 Minimum of Numbers java
  programme/minimum-of-numbers/README.md
  programme/minimum-of-numbers/index.md
  programme/minimum-of-numbers/solution.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#279 Add two numbers Python
  programme/add-two-numbers/README.md
  programme/add-two-numbers/index.md
  programme/add-two-numbers/solution.py
Labels: good first issue, 📝 content, ready-to-deploy, Python

#287 multiply-two-numbers
  multiply-two-numbers/README.md
  multiply-two-numbers/index.md
  multiply-two-numbers/solution.py
Labels: good first issue, 📝 content, Python

#286 Add : Code of Fibonacci series without recursion in python
  programme/Fibonacci-nth-Python/Readme.md
  programme/Fibonacci-nth-Python/fibonacci-nth-python.py
  programme/Fibonacci-nth-Python/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#294 Create solution.c
  programme/rupee-to-paise/README.md
  programme/rupee-to-paise/index.md
  programme/rupee-to-paise/solution.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#295 Added Fibonacci series without recursion in CPP
  programme/fibonaci-series-without-using-recursion/README.md
  programme/fibonaci-series-without-using-recursion/solution.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#297 Added C Code for checking Prime number
  programme/check-prime-number/README.md
  programme/check-prime-number/index.md
  programme/check-prime-number/solution.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#299 Added solution.c for fibonnaci-series-using-recursion
  programme/fibonnaci-series-using-recursion/README.md
  programme/fibonnaci-series-using-recursion/index.md
  programme/fibonnaci-series-using-recursion/solution.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#298 Added code for checking palindrome number.
  programme/README.md
  programme/palindrome-number/README.md
  programme/palindrome-number/index.md
  programme/palindrome-number/solution.c
  programme/palindrome-number/solution.cpp
  programme/palindrome-number/solution.java
  programme/palindrome-number/solution.py
Labels: good first issue, 📝 content, C, ready-to-deploy, Python, C++, Java

#303 Added C++ code for checking prime number
  programme/check-prime-number/README.md
  programme/check-prime-number/solution.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#316 Program to subtract two numbers in Python, C, and C++
  programme/subtract-two-numbers/README.md
  programme/subtract-two-numbers/index.md
  programme/subtract-two-numbers/subtract-two-numbers.c
  programme/subtract-two-numbers/subtract-two-numbers.cpp
  programme/subtract-two-numbers/subtract-two-numbers.py
Labels: good first issue, 📝 content, C, ready-to-deploy, Python, C++

#317 wrote cpp + java programs for rupee to paise conversion
  programme/rupee-to-paise/README.md
  programme/rupee-to-paise/index.md
  programme/rupee-to-paise/rs-to-p.cpp
  programme/rupee-to-paise/rs_to_p.java
Labels: good first issue, 📝 content, ready-to-deploy, C++, Java

#319 Added code for Subtraction of 2 numbers and pattern-2
  programme/pattern-2/README.md
  programme/pattern-2/index.md
  programme/pattern-2/pattern-2.c
  programme/pattern-2/pattern-2.cpp
  programme/pattern-2/pattern-2.java
  programme/subtract-two-numbers/README.md
  programme/subtract-two-numbers/index.md
  programme/subtract-two-numbers/subtract-two-numbers.java
Labels: good first issue, 📝 content, C, ready-to-deploy, C++, Java

#329 added square of a number in java, updated README.md and Index.md
  programme/square-of-number/README.md
  programme/square-of-number/index.md
  programme/square-of-number/square.java
Labels: good first issue, 📝 content, ready-to-deploy, Java

#342 division of two numbers
  programme/README.md
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide-two-numbers.c
  programme/divide-two-numbers/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#343 Taking two inputs instead of one
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide-two-numbers.c
  programme/divide-two-numbers/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#380 created area-of-right-triangle folder, area.java, README.md, index.md
  programme/README.md
  programme/area-of-right-angle-triangle/README.md
  programme/area-of-right-angle-triangle/area.java
  programme/area-of-right-angle-triangle/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#384 fixes #366
  programme/area-of-square/README.md
  programme/area-of-square/area-of-squara.java
  programme/area-of-square/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#383 adding the area of the right triangle program in python
  programme/area-of-right-angle-triangle/README.md
  programme/area-of-right-angle-triangle/area.py
  programme/area-of-right-angle-triangle/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#381 computes the area of a square
  programme/area-of-rectangle/README.md
  programme/area-of-rectangle/area-of-rectangle.c
  programme/area-of-rectangle/index.md
  programme/area-of-square/README.md
  programme/area-of-square/area-of-square.c
  programme/area-of-square/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#385 adding the area-of-triangle.py calculator app
  programme/area-of-triangle/README.md
  programme/area-of-triangle/area-of-triangle.py
  programme/area-of-triangle/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#386 Leap year checking program added #333
  programme/check-leap-year/README.md
  programme/check-leap-year/check-leap-year.py
  programme/check-leap-year/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#387 Calculates the area of a right angle triangle
  programme/area-of-right-angle-triangle/README.md
  programme/area-of-right-angle-triangle/area-of-right-angle-triangle.c
  programme/area-of-right-angle-triangle/area-of-right-angle-triangle.java
  programme/area-of-right-angle-triangle/area-of-right-angle-triangle.py
  programme/area-of-right-angle-triangle/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#390 Area of Square Python
  programme/area-of-rectangle/README.md
  programme/area-of-rectangle/area-of-rectangle.py
  programme/area-of-rectangle/index.md
  programme/area-of-square/README.md
  programme/area-of-square/area-of-square.py
  programme/area-of-square/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#389 divide_two_numbers.java
  programme/divide-two-numbers/README.md
  programme/divide-two-numbers/divide-two-numbers.java
  programme/divide-two-numbers/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#388 Add : Number to Strings and reverse of a number code
  programme/number-to-string/README.md
  programme/number-to-string/index.md
  programme/number-to-string/number-to-string.cpp
  programme/number-to-string/number-to-string.java
  programme/reverse-of-a-number/README.md
  programme/reverse-of-a-number/index.md
  programme/reverse-of-a-number/reverse-of-number.c
  programme/reverse-of-a-number/reverse-of-number.cpp
  programme/reverse-of-a-number/reverse-of-number.cs
  programme/reverse-of-a-number/reverse-of-number.java
  programme/reverse-of-a-number/reverse-of-number.py
Labels: good first issue, 📝 content, C, ready-to-deploy, C++, Java

#396 Add decimal-to-binary in C and in Python
  programme/decimal-to-binary/README.md
  programme/decimal-to-binary/decimal-to-binary.c
  programme/decimal-to-binary/decimal-to-binary.py
  programme/decimal-to-binary/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy, Python

#393 Add min.c
  programme/minimum-of-numbers/README.md
  programme/minimum-of-numbers/index.md
  programme/minimum-of-numbers/min.c
Labels: good first issue, 📝 content, C, ready-to-deploy

#395 Add : Number Triangle Pattern and decimal to binary code in c
  programme/README.md
  programme/decimal-to-binary/README.md
  programme/decimal-to-binary/decimal-to-binary.c
  programme/decimal-to-binary/decimal-to-binary.cpp
  programme/decimal-to-binary/decimal_to_binary.java
  programme/decimal-to-binary/index.md
  programme/number-triangle-pattern/README.md
  programme/number-triangle-pattern/index.md
  programme/number-triangle-pattern/number-triangle-pattern.c
Labels: good first issue, 📝 content, C, ready-to-deploy, C++, Java

#397 added area of right angle triangle in c++ and updated README.md
  programme/area-of-right-angle-triangle/README.md
  programme/area-of-right-angle-triangle/area-of-right-angle-triangle.cpp
Labels: good first issue, 📝 content, ready-to-deploy, C++

#398 #51 helloworld
  programme/hello-world/README.md
  programme/hello-world/hello-world.c
  programme/hello-world/index.md
Labels: good first issue, 📝 content, C, ready-to-deploy

#401 Create area-of-triangle.cpp
  programme/area-of-triangle/README.md
  programme/area-of-triangle/area-of-triangle.cpp
  programme/area-of-triangle/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#400 Resolves issue #364
  programme/area-of-square/README.md
  programme/area-of-square/area-of-square.cs
  programme/area-of-square/index.md
  programme/decimal-to-binary/README.md
  programme/decimal-to-binary/decimal-to-binary.cs
  programme/decimal-to-binary/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C#

#407 Create add-two-numbers.cpp
  programme/add-two-numbers/README.md
  programme/add-two-numbers/add-two-numbers.cpp
  programme/add-two-numbers/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#409 Create area-of-square.cpp
  programme/area-of-square/README.md
  programme/area-of-square/area-of-square.cpp
  programme/area-of-square/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#408 Create area-of-rectangle.cpp
  programme/area-of-rectangle/README.md
  programme/area-of-rectangle/area-of-rectangle.cpp
  programme/area-of-rectangle/index.md
Labels: good first issue, 📝 content, ready-to-deploy, C++

#404 Solves issue #311
  programme/subtract-two-numbers/README.md
  programme/subtract-two-numbers/index.md
  programme/subtract-two-numbers/subtract-two-numbers.cs
Labels: good first issue, 📝 content, ready-to-deploy, C#

#403 Hours to seconds
  programme/hours-to-seconds/README.md
  programme/hours-to-seconds/hours-to-seconds.py
  programme/hours-to-seconds/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Python

#410 Add : Number Triangle Pattern in cpp, java, python
  programme/number-triangle-pattern/README.md
  programme/number-triangle-pattern/number-triangle-pattern.cpp
  programme/number-triangle-pattern/number-triangle-pattern.py
  programme/number-triangle-pattern/number_triangle_pattern.java
Labels: 📝 content, ready-to-deploy, Python, C++, Java

#402 Underwork
  programme/fibonnaci-series-using-recursion/README.md
  programme/fibonnaci-series-using-recursion/fibonaci-recursion.java
  programme/fibonnaci-series-using-recursion/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java

#399 Add files via upload
  programme/area-of-triangle/README.md
  programme/area-of-triangle/area-of-triangle.java
  programme/area-of-triangle/index.md
Labels: good first issue, 📝 content, ready-to-deploy, Java
